// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Category struct {
	ID          int32       `json:"id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
}

type Product struct {
	ID            int32       `json:"id"`
	Name          string      `json:"name"`
	Description   pgtype.Text `json:"description"`
	Price         float64     `json:"price"`
	StockQuantity int32       `json:"stock_quantity"`
	Status        string      `json:"status"`
	ImageUrl      pgtype.Text `json:"image_url"`
	CreatedAt     time.Time   `json:"created_at"`
	UpdatedAt     time.Time   `json:"updated_at"`
}

type ProductCategory struct {
	ProductID  int32 `json:"product_id"`
	CategoryID int32 `json:"category_id"`
}

type Review struct {
	ID        int32       `json:"id"`
	ProductID int32       `json:"product_id"`
	UserID    int32       `json:"user_id"`
	Rating    int32       `json:"rating"`
	Comment   pgtype.Text `json:"comment"`
	CreatedAt time.Time   `json:"created_at"`
	UpdatedAt time.Time   `json:"updated_at"`
}

type Session struct {
	ID           uuid.UUID `json:"id"`
	Username     string    `json:"username"`
	RefreshToken string    `json:"refresh_token"`
	UserAgent    string    `json:"user_agent"`
	ClientIp     string    `json:"client_ip"`
	IsBlocked    bool      `json:"is_blocked"`
	ExpiresAt    time.Time `json:"expires_at"`
	CreatedAt    time.Time `json:"created_at"`
}

type User struct {
	ID                int32       `json:"id"`
	ExtID             uuid.UUID   `json:"ext_id"`
	Username          string      `json:"username"`
	HashedPassword    string      `json:"hashed_password"`
	FullName          pgtype.Text `json:"full_name"`
	Email             string      `json:"email"`
	Role              pgtype.Text `json:"role"`
	PasswordChangedAt time.Time   `json:"password_changed_at"`
	CreatedAt         time.Time   `json:"created_at"`
	UpdatedAt         time.Time   `json:"updated_at"`
}

type Wishlist struct {
	UserID    int32     `json:"user_id"`
	ProductID int32     `json:"product_id"`
	AddedAt   time.Time `json:"added_at"`
}
