// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddProductCategory(ctx context.Context, arg AddProductCategoryParams) error
	CountCategories(ctx context.Context) (int64, error)
	CountCategoriesWithName(ctx context.Context, name string) (int64, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreateProductCategory(ctx context.Context, arg CreateProductCategoryParams) (ProductCategory, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteCategory(ctx context.Context, id int32) error
	DeleteProduct(ctx context.Context, id int32) error
	DeleteProductCategories(ctx context.Context, productID int32) error
	GetCategory(ctx context.Context, id int32) (Category, error)
	GetCategoryByName(ctx context.Context, name string) (Category, error)
	GetProduct(ctx context.Context, id int32) (GetProductRow, error)
	GetProductCategories(ctx context.Context, productID int32) ([]Category, error)
	GetProductReviews(ctx context.Context, productID int32) ([]GetProductReviewsRow, error)
	GetSession(ctx context.Context, id uuid.UUID) (Session, error)
	GetUser(ctx context.Context, username string) (User, error)
	ListCategoriesWithPagination(ctx context.Context, arg ListCategoriesWithPaginationParams) ([]Category, error)
	RemoveAllProductCategories(ctx context.Context, productID int32) error
	RemoveProductCategory(ctx context.Context, arg RemoveProductCategoryParams) error
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error)
}

var _ Querier = (*Queries)(nil)
