### Variables
@baseUrl = http://localhost:8081
@authToken = "enter_your_access_token"
# Get from login api

### Create User
POST {{baseUrl}}/api/auth/register
Content-Type: application/json

{
  "username": "testuser2drrr3",
  "password": "passworrrrd123",
  "full_name": "Test User",
  "email": "tesd1dss3@example.com"
}

### Login User
# This will return access and refresh tokens
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
  "username": "testuser2drrr3",
  "password": "passworrrrd123"
}

### Renew Access Token
# Use this when your access token expires but refresh token is still valid
POST {{baseUrl}}/tokens/renew_access
Content-Type: application/json

{
  "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAwNmI4MGU0LTdiM2EtNGQ0Mi1iODEzLTM0NDRiNzlkMjFhNyIsInVzZXJuYW1lIjoidGVzdHVzZXIyZDMiLCJyb2xlIjoidXNlciIsImlzc3VlZF9hdCI6IjIwMjUtMDQtMTlUMTk6MTg6MjQuODM1Nzg0KzA3OjAwIiwiZXhwaXJlZF9hdCI6IjIwMjUtMDQtMjBUMTk6MTg6MjQuODM1Nzg0KzA3OjAwIn0.Z6WPIN9CK7901aQkGFNRPUYysfDrG4cN6a4YzgysE_Q"
}

# ================================ CATEGORY ====================================

### Create Category
POST {{baseUrl}}/api/categories
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "name": "Category1",
  "description": "Category1"
}

### List Categories
GET {{baseUrl}}/api/categories?page=1&limit=10
Authorization: Bearer {{authToken}}

### Get Category Details
GET {{baseUrl}}/api/categories/1
Authorization: Bearer {{authToken}}

### Update Category
PUT {{baseUrl}}/api/categories/1
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "name": "Updated Electronics",
  "description": "Updated description for electronic devices and gadgets"
}

### Delete Category
DELETE {{baseUrl}}/api/categories/2
Authorization: Bearer {{authToken}}


### ========================== PRODUCTS API ====================================

### Create Product
# status: IN_STOCK or OUT_OF_STOCK
POST {{baseUrl}}/api/products
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "name": "anthanh",
  "description": "This is anthanh",
  "price": 99.99999,
  "stock_quantity": 1232,
  "status": "OUT_OF_STOCK",
  "image_url": "https://example.com/test-product.jpg",
  "category_ids": [1, 2]
}

### Get Product Details
GET {{baseUrl}}/api/products/1
Authorization: Bearer {{authToken}}

### Delete Product
DELETE {{baseUrl}}/api/products/2
Authorization: Bearer {{authToken}}

### Update Product
PUT {{baseUrl}}/api/products/2
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "name": "Updated Product 2",
  "description": "This is an updated product description 22222",
  "price": 22.22,
  "stock_quantity": 22,
  "status": "IN_STOCK",
  "image_url": "https://example.com/updated-product.jpg 22",
  "category_ids": [2]
}

### List Products (Basic)
GET {{baseUrl}}/api/products?page=1&limit=10
Authorization: Bearer {{authToken}}

### List Products (Filter by Status) IN_STOCK
GET {{baseUrl}}/api/products?page=1&limit=10&status=IN_STOCK
Authorization: Bearer {{authToken}}

### List Products (Filter by Status) OUT_OF_STOCK
GET {{baseUrl}}/api/products?page=1&limit=10&status=OUT_OF_STOCK
Authorization: Bearer {{authToken}}

### List Products (Search by Name)
GET {{baseUrl}}/api/products?page=1&limit=10&search_product_name=tes
Authorization: Bearer {{authToken}}

### List Products (Combined Filters)
GET {{baseUrl}}/api/products?page=1&limit=10&status=IN_STOCK&search_product_name=an
Authorization: Bearer {{authToken}}

### ========================== Dashboard =======================================

### Get Dashboard Summary
GET {{baseUrl}}/api/dashboard/summary
Authorization: Bearer {{authToken}}
