token:
  accessTokenDuration: 15m
  refreshTokenDuration: 24h
  tokenSymmetricKey: 12345678901234567890123456789012 # 32 byte
database:
  host: postgres
  port: 5432
  username: root
  password: secret
  database: bfast
cache:
  type: redis
  host: redis
  port: 6379
  username:
  password:
http:
  address: 0.0.0.0:8081
log:
  level: info
