version: "2"
sql:
  - engine: "postgresql"
    schema: "../internal/dataaccess/database/migration"
    queries: "../internal/dataaccess/database/query"
    gen:
      go:
        package: "db"
        out: "../internal/dataaccess/database/sqlc"
        sql_package: "pgx/v5"
        emit_json_tags: true
        emit_interface: true
        emit_empty_slices: true
        overrides:
        - db_type: "timestamptz"
          go_type: "time.Time"
        - db_type: "uuid"
          go_type: "github.com/google/uuid.UUID"
